POST http://localhost:3003/turma
Content-Type: application/json
{
    "nome": "Zuckerber",
    "modulo": 1
}

###

GET http://localhost:3003/turma
Content-Type: application/json

###

PUT http://localhost:3003/turma
Content-Type: application/json

###

POST http://localhost:3003/estudante
Content-Type: application/json
{
    "nome": "Aninha",
    "email": "aninha@gmail.com",
    "data_nasc": "22/06/2000"
}

###

GET http://localhost:3003/estudante
Content-Type: application/json

###

PUT http://localhost:3003/estudante
Content-Type: application/json

###

POST http://localhost:3003/docente
Content-Type: application/json

### 

GET http://localhost:3003/docente
Content-Type: application/json

### 

PUT http://localhost:3003/docente
Content-Type: application/json